### ISSUE TITLE
V1.3.0 Regression: control is not displayed anymore on Android

### ISSUE THREAD

**Issue by nbsoftware** [alexrainman/SegmentedControl#36]
Once code has been update to fix the few breaking changes from V1.2.4, code builds successfully but control does not show anymore.

**Comment by alexrainman** [comment]
How you are using the control? so i can reproduce the issue.

**Comment by alexrainman** [comment]
Fixed.

**Comment by chrisfoulds** [comment]
Still not appearing using 1.3.1 for me even after removing and readding nuget , had to drop back to 1.2.4

**Comment by adiiaditya** [comment]
Still not appearing.

**Comment by bulubuloa** [comment]
i have a same problem, control is not display on android
